### ISSUE TITLE
use for other dataset

### ISSUE THREAD

**Issue by liu-x-p** [JakobPoncelet/FHVAE_TF2#4]
Hi.
I have tried your model with TIMIT dataset. 
How could I use the model to process other datasets such as ZS2019 dataset?

**Comment by JakobPoncelet** [comment]
Hi. 
You only have to create a wav.scp file.
You can then use the scripts to extract features, as in the TIMIT preprocessing example.

**Comment by liu-x-p** [comment]
@JakobPoncelet Thank you! I will try to use it.
